name: EcoBits
version: ${projectVersion}
main: com.willfp.ecobits.EcoBitsPlugin
api-version: 1.19
load: STARTUP

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: Vault
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false
permissions:
  ecobits.*:
    description: All EcoBits permissions
    default: op
    children:
      ecobits.command.*: true
  ecobits.command.*:
    description: All commands
    default: op
    children:
      ecobits.command.reload: true
      ecobits.command.give: true
      ecobits.command.givesilent: true
      ecobits.command.get: true
      ecobits.command.set: true
      ecobits.command.reset: true
      ecobits.command.pay: true
      ecobits.command.take: true
      ecobits.command.takesilent: true
      ecobits.command.balance: true

  ecobits.command.reload:
    description: Allows reloading the config
    default: op
  ecobits.command.give:
    description: Gives a currency
    default: op
  ecobits.command.take:
    description: Takes a currency
    default: op
  ecobits.command.takesilent:
    description: Takes a currency silently
    default: op
  ecobits.command.givesilent:
    description: Gives a currency silently
    default: op
  ecobits.command.get:
    description: Gets a currency
    default: op
  ecobits.command.set:
    description: Sets a currency
    default: op
  ecobits.command.reset:
    description: Resets a currency
    default: op
  ecobits.command.pay:
    description: Pays a player
    default: true
  ecobits.command.balance:
    description: Views your balance
    default: true